-- MySQL Script generated by MySQL Workbench
-- 05/13/16 20:55:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dms` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `dms` ;

-- -----------------------------------------------------
-- Table `dms`.`dorm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`dorm` (
  `dorm_num` CHAR(10) NOT NULL,
  `region` CHAR(1) NOT NULL,
  `build_num` TINYINT NOT NULL,
  `part` CHAR(1) NOT NULL,
  `floor` TINYINT NOT NULL,
  `total` CHAR(2) NULL,
  PRIMARY KEY (`dorm_num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dms`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`students` (
  `stu_id` CHAR(10) NOT NULL,
  `stu_name` CHAR(10) NOT NULL,
  `sex` CHAR(1) NOT NULL,
  `dorm_num` CHAR(10) NOT NULL,
  `bed_num` CHAR(1) NOT NULL,
  `grade` CHAR(4) NOT NULL,
  `depart` CHAR(20) NULL,
  `major` CHAR(20) NULL,
  `class` CHAR(1) NULL,
  `phone` CHAR(11) NULL,
  `email` CHAR(32) NULL,
  `ethnic` CHAR(10) NULL,
  `stu_comment` TEXT NULL,
  PRIMARY KEY (`stu_id`),
  INDEX `stu_dorm_idx` (`dorm_num` ASC),
  CONSTRAINT `stu_dorm`
    FOREIGN KEY (`dorm_num`)
    REFERENCES `dms`.`dorm` (`dorm_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dms`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(64) NOT NULL,
  `user_password_hash` VARCHAR(255) NOT NULL,
  `user_email` VARCHAR(64) NOT NULL,
  `user_level` VARCHAR(2) NULL,
  `user_role` VARCHAR(64) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC),
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dms`.`routine_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`routine_list` (
  `date` CHAR(10) NOT NULL,
  `dorm_num` CHAR(10) NOT NULL,
  `add_floor` CHAR(10) NOT NULL,
  `user_name` VARCHAR(64) NOT NULL,
  `comments` VARCHAR(128) NULL,
  `score` CHAR(3) NOT NULL,
  `score_t` CHAR(3) NOT NULL,
  `wc_balcony` CHAR(2) NOT NULL,
  `bed` CHAR(2) NOT NULL,
  `desk_cupboard` CHAR(2) NOT NULL,
  `ground` CHAR(2) NOT NULL,
  `security` CHAR(2) NOT NULL,
  PRIMARY KEY (`date`, `dorm_num`),
  INDEX `list_dorm_idx` (`dorm_num` ASC),
  INDEX `list_users_idx` (`user_name` ASC),
  CONSTRAINT `list_dorm`
    FOREIGN KEY (`dorm_num`)
    REFERENCES `dms`.`dorm` (`dorm_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `list_users`
    FOREIGN KEY (`user_name`)
    REFERENCES `dms`.`users` (`user_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dms`.`routine_add`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`routine_add` (
  `routine_add_id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` CHAR(10) NOT NULL,
  `user_name` VARCHAR(64) NOT NULL,
  `routine_add_action` CHAR(10) NOT NULL,
  `dorm_num_sum` TEXT NOT NULL,
  `add_time` CHAR(20) NOT NULL,
  `add_floor` CHAR(10) NOT NULL,
  PRIMARY KEY (`routine_add_id`),
  INDEX `date_users_idx` (`user_name` ASC),
  CONSTRAINT `date_users`
    FOREIGN KEY (`user_name`)
    REFERENCES `dms`.`users` (`user_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dms`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dms`.`log` (
  `log_id` INT(11) NOT NULL AUTO_INCREMENT,
  `log_time` CHAR(20) NOT NULL,
  `user_name` VARCHAR(64) NOT NULL,
  `action` TEXT NOT NULL,
  `ipa` VARCHAR(45) NULL,
  `ipb` VARCHAR(45) NULL,
  `user_agent` TEXT NULL,
  PRIMARY KEY (`log_id`),
  INDEX `log_users_idx` (`user_name` ASC),
  CONSTRAINT `log_users`
    FOREIGN KEY (`user_name`)
    REFERENCES `dms`.`users` (`user_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
